"""Thresholding / AboveThreshold operator research package."""

from operators.thresholding.math import (
    EVALUATION_METHOD_DET,
    EVALUATION_METHOD_NOISY,
    LEVEL_STATUS,
    OPERATOR,
    THEOREM_ID_DETERMINISTIC,
    THEOREM_ID_NOISY,
    THEOREM_STATEMENT_DET,
    THEOREM_STATEMENT_NOISY,
    SequentialLevel,
    ThresholdInstance,
    above_threshold,
    adversarial_break_fail,
    adversarial_break_pass,
    certified_set,
    fail_preserved,
    first_crossing,
    noisy_first_crossing,
    pass_preserved,
    unstable_region,
)
from operators.thresholding.verify import (
    claim_is_bounded_noise_threshold,
    claim_is_threshold_preservation,
    verify_bounded_noise_threshold,
    verify_threshold_preservation,
)
from operators.thresholding.workflow import (
    run_bounded_noise_threshold_workflow,
    run_threshold_preservation_workflow,
)

__all__ = [
    "OPERATOR",
    "THEOREM_ID_DETERMINISTIC",
    "THEOREM_ID_NOISY",
    "EVALUATION_METHOD_DET",
    "EVALUATION_METHOD_NOISY",
    "THEOREM_STATEMENT_DET",
    "THEOREM_STATEMENT_NOISY",
    "LEVEL_STATUS",
    "SequentialLevel",
    "ThresholdInstance",
    "above_threshold",
    "pass_preserved",
    "fail_preserved",
    "unstable_region",
    "adversarial_break_pass",
    "adversarial_break_fail",
    "certified_set",
    "first_crossing",
    "noisy_first_crossing",
    "claim_is_threshold_preservation",
    "claim_is_bounded_noise_threshold",
    "verify_threshold_preservation",
    "verify_bounded_noise_threshold",
    "run_threshold_preservation_workflow",
    "run_bounded_noise_threshold_workflow",
]
